name = "ofw-pesorate"
compatibility_date = "2024-03-21"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "ofw_pesorate_db"
database_id = "51d58731-0d5c-41ad-b056-7d36e29fab0d"

[vars]
CF_ADMIN_TOKEN = "ofwAk026"
CF_FIXER_KEY = "566e5ce2bbb50f23733c34b6b07146b2"
